package com.apptolast.customlogin.util

data class CountryCallingCode(val flag: String, val name: String, val dialCode: String) {
    val displayLabel: String get() = "$flag $dialCode"
}

val COMMON_COUNTRIES: List<CountryCallingCode> = listOf(
    CountryCallingCode("🇩🇿", "Algeria", "+213"),
    CountryCallingCode("🇦🇷", "Argentina", "+54"),
    CountryCallingCode("🇦🇺", "Australia", "+61"),
    CountryCallingCode("🇦🇹", "Austria", "+43"),
    CountryCallingCode("🇧🇪", "Belgium", "+32"),
    CountryCallingCode("🇧🇷", "Brazil", "+55"),
    CountryCallingCode("🇨🇦", "Canada", "+1"),
    CountryCallingCode("🇨🇱", "Chile", "+56"),
    CountryCallingCode("🇨🇳", "China", "+86"),
    CountryCallingCode("🇨🇴", "Colombia", "+57"),
    CountryCallingCode("🇭🇷", "Croatia", "+385"),
    CountryCallingCode("🇨🇿", "Czech Republic", "+420"),
    CountryCallingCode("🇩🇰", "Denmark", "+45"),
    CountryCallingCode("🇪🇬", "Egypt", "+20"),
    CountryCallingCode("🇫🇮", "Finland", "+358"),
    CountryCallingCode("🇫🇷", "France", "+33"),
    CountryCallingCode("🇩🇪", "Germany", "+49"),
    CountryCallingCode("🇬🇷", "Greece", "+30"),
    CountryCallingCode("🇭🇰", "Hong Kong", "+852"),
    CountryCallingCode("🇭🇺", "Hungary", "+36"),
    CountryCallingCode("🇮🇳", "India", "+91"),
    CountryCallingCode("🇮🇩", "Indonesia", "+62"),
    CountryCallingCode("🇮🇪", "Ireland", "+353"),
    CountryCallingCode("🇮🇱", "Israel", "+972"),
    CountryCallingCode("🇮🇹", "Italy", "+39"),
    CountryCallingCode("🇯🇵", "Japan", "+81"),
    CountryCallingCode("🇲🇾", "Malaysia", "+60"),
    CountryCallingCode("🇲🇽", "Mexico", "+52"),
    CountryCallingCode("🇳🇱", "Netherlands", "+31"),
    CountryCallingCode("🇳🇿", "New Zealand", "+64"),
    CountryCallingCode("🇳🇬", "Nigeria", "+234"),
    CountryCallingCode("🇳🇴", "Norway", "+47"),
    CountryCallingCode("🇵🇰", "Pakistan", "+92"),
    CountryCallingCode("🇵🇪", "Peru", "+51"),
    CountryCallingCode("🇵🇭", "Philippines", "+63"),
    CountryCallingCode("🇵🇱", "Poland", "+48"),
    CountryCallingCode("🇵🇹", "Portugal", "+351"),
    CountryCallingCode("🇷🇴", "Romania", "+40"),
    CountryCallingCode("🇷🇺", "Russia", "+7"),
    CountryCallingCode("🇸🇦", "Saudi Arabia", "+966"),
    CountryCallingCode("🇿🇦", "South Africa", "+27"),
    CountryCallingCode("🇰🇷", "South Korea", "+82"),
    CountryCallingCode("🇪🇸", "Spain", "+34"),
    CountryCallingCode("🇸🇪", "Sweden", "+46"),
    CountryCallingCode("🇨🇭", "Switzerland", "+41"),
    CountryCallingCode("🇹🇼", "Taiwan", "+886"),
    CountryCallingCode("🇹🇭", "Thailand", "+66"),
    CountryCallingCode("🇹🇷", "Turkey", "+90"),
    CountryCallingCode("🇺🇦", "Ukraine", "+380"),
    CountryCallingCode("🇦🇪", "UAE", "+971"),
    CountryCallingCode("🇬🇧", "United Kingdom", "+44"),
    CountryCallingCode("🇺🇸", "United States", "+1"),
    CountryCallingCode("🇻🇳", "Vietnam", "+84"),
)
